name: shellcheck
on: [pull_request]

jobs:
  shellcheck:
    name: check / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: shellcheck
        uses: reviewdog/action-shellcheck@6e0e63d1750d02d761b3df0f2c5ba9f9ac4a9ed7 # v1.29.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          pattern: "*.sh"
          fail_level: any
